### ISSUE TITLE
Bounty created by direct Smart Contract interaction not showing in API

### ISSUE THREAD

**Issue by edsonayllon** [Bounties-Network/BountiesAPI#300]
New bounty was created in Rinkeby: https://rinkeby.etherscan.io/address/0x38f1886081759f7d352c28984908d04e8d2205a6

When querying for bounties with the issuer specified in the successful `issueAndContribute` call, no bounties were found. This was queried using the Rinkeby API for Standard Bounties, http://rinkeby.api.bounties.network/.

**Comment by mbeylin** [comment]
Hey Edison, I have a few questions:

- could you link to the transaction which was used to create the bounty?
- when posting the bounty, did you supply a correct IPFS hash?
- If so, did the corresponding JSON object comply with our schema?
- If so, which IPFS endpoint did you use when uploading the JSON object?

**Comment by edsonayllon** [comment]
2 Transactions:
- https://rinkeby.etherscan.io/tx/0x990146a87f43bd0f01ca4ef2f071b36fe3bd4b98e0482eae04b393e2af5a6dbf
- https://rinkeby.etherscan.io/tx/0x1b2424ee5a194300eeda6b33bd439b492f7a62fc4a42d30d24aa8c048ba702a7

IPFS Hash: https://ipfs.globalupload.io/QmSMFK3ckAWmh5kRRfZ5ZJDfP8zYHUeLWwhsPKxbAx5Tqn

I guess, it wasn't JSON, nor did it use the schema, that's probably the issue.

**Comment by mbeylin** [comment]
Yeah that makes sense. It appears our IPFS node thankfully did indeed have this file, so complying with the schema would have ensured this bounty would have been successfully added. Best of luck, I'll mark this issue as resolved.

**Comment by edsonayllon** [comment]
So, I tested with a new IPFS Upload: https://ipfs.io/ipfs/QmNsu3fZ9sS9SZhUrSxxHwGpgvohstKe7wyTfzYvcQJzzZ. Still not showing in the API. I uploaded it as JSON. Is something wrong with the format?

Transaction: 0x3989401d333653d743235fdd9310a2ff8e7093ebef2ee6fcd6cd957d9b51838c

**Comment by mbeylin** [comment]
Edison,

My sincerest apologies, it seems our StandardBounties docs were not up to date with the latest schema version we use:
```{
  payload: {
    title: // a string representing the title of the bounty
    description: // a string representing the description of the bounty, including all requirements
    fulfillmentAmount: // an integer amount that will be paid out to fufillers
    categories: // an array of strings, representing the categories of tasks which are being requested
    expectedRevisions: // an integer of how many times the spec is expected to be adjusted during fulfillment
    difficulty: // a string representing how difficult this bounty is (one of: easy, medium, hard)
    privateFulfillments: // boolean desrcibing whether fulfillments are only visible to the issuer
    fulfillersNeedApproval: // boolean that forces users to be approved before fulfilling the bounty

    // ------- add optional fields here -------
    ipfsFilename: // a string representing the name of the file
    ipfsHash: // the IPFS hash of the directory which can be used to access the file
    webReferenceURL: // the link to a relevant web reference (ie github issue)
  },
  meta: {
    platform: // a string representing the original posting platform (ie 'gitcoin')
    schemaVersion: // a string representing the version number (ie '0.1')
    schemaName: // a string representing the name of the schema (ie 'standardSchema' or 'gitcoinSchema')
  }
}```
If you try issuing using this schema, it should work well. Please update me on your results.

**Comment by edsonayllon** [comment]
I still don't see the bounty. 

- Transaction: https://rinkeby.etherscan.io/tx/0x9eefb335d12e09f700c91d6a6788a69bc9a7b6474da72ac24fdb5ef096dc4039
- IPFS Hash: https://ipfs.globalupload.io/QmXsQLCQESh2SwdNQgWbeurruF5nSkL7Q6b8hthMjkEJf2
- API Call: https://rinkeby.api.bounties.network/bounty/?issuer=0xBBAac64b4E4499aa40DB238FaA8Ac00BAc50811B

Also, https://rinkeby.api.bounties.network makes calls to newrinkeby.api.bounties.network which serves no response to any request.

**Comment by edsonayllon** [comment]
Actually, it does find the bounty by platform. Is there any way for the bounty to be queried by issuer with the new Schema? https://rinkeby.api.bounties.network/bounty/?platform__in=doastack

**Comment by edsonayllon** [comment]
Nevermind, it does work searching by issuer. 
https://rinkeby.api.bounties.network/bounty/?platform__in=doastack&platform=&issuer=0xbbaac64b4e4499aa40db238faa8ac00bac50811b

I'll close this issue. However,  I would look into why the Rinkeby API is querying a `newrinkeby.api`, as that subdomain doesn't exist.
